#!/bin/bash

function send_notification() {
	volume=$(pamixer --get-volume)
	notify-send -a "changevolume" -u low -r "81" -h string:hlcolor:#d79921 -h int:value:"$volume" "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer -u
	pamixer -i 5 #--allow-boost
	send_notification $1
	;;
down)
	pamixer -u
	pamixer -d 5 #--allow-boost
	send_notification $1
	;;
mute)
	pamixer -t
	if $(pamixer --get-mute); then
		notify-send -a "changevolume" -t 2000 -r 81 -u low "Muted"
	else
		send_notification up
	fi
	;;
esac
