#!/bin/bash
# Dependencies: grimblast-git, tesseract-ocr, wl-clipboard, sdcv

TEMP_SCREENSHOT=$(mktemp /tmp/screenshot-XXXXXX.png) # Temporary file for screenshot

grimblast --freeze copysave area "$TEMP_SCREENSHOT" > /dev/null 2>&1 || { echo "No screenshot taken."; rm "$TEMP_SCREENSHOT"; exit 1; }

OCR_RESULT=$(tesseract -l pol "$TEMP_SCREENSHOT" stdout 2>/dev/null) # OCR
rm "$TEMP_SCREENSHOT" # Clean up screenshot file

if [ -n "$OCR_RESULT" ]; then
    # Remove lines that contain only a single character
    OCR_RESULT=$(echo "$OCR_RESULT" | grep -v '^.$')

    echo "$OCR_RESULT" | wl-copy # Copy to clipboard
    echo "$OCR_RESULT" # Output OCR result to terminal
    notify-send "Text copied to clipboard"

    # Unique class for our term window
    TERM_CLASS="sdcv"

    # Use xdotool to search for a window with our unique class and close it
    hyprctl dispatch closewindow "$TERM_CLASS"

    # Open term with a unique class and run sdcv with the OCR result
    foot -a "$TERM_CLASS" -H sdcv -c -n "$OCR_RESULT"
else
    echo "No text found."
    notify-send "No text found" 
fi

