#!/bin/bash

rofi_command="rofi -dmenu -theme $HOME/.config/rofi/themes/quicklinks.rasi -i -p "Q-LINKS:" -selected-row 0"
dmenu_command="dmenu -l 25 -i -p "Q-LINKS:""
tofi_command="tofi --width 300 --height 300 --prompt-text="Q-LINKS:""
hypr_scripts="~/.config/hypr/scripts"

if [ "$1" == "--wayland" ]; then
  NVIM="foot -T neovim -a neovim nvim"
  FM="foot -T yazi -a yazi yazi"
  LAUNCHER="$tofi_command"
elif [ "$1" == "--x11" ]; then
  NVIM="alacritty --class neovim -e nvim"
  FM="alacritty --class yazi -e yazi"
  LAUNCHER="$rofi_command"
else
  echo "Options:"
  echo "--wayland"
  echo "--x11"
  exit 1
fi

function ags_restart() {
    if pgrep "ags" > /dev/null; then
        pkill ags
    fi
    ags -c ~/nixos-config/modules/ags/config.js &
}

# Define options in a format "label:command"
options=(
  "NIXOS-VSCODE:              cd ~/nixos-config && codium ~/nixos-config"
  "NIXOS-NEOVIM:              cd ~/nixos-config && $NVIM ."
  "HYPRLAND:                  cd ~/nixos-config && $NVIM ~/nixos-config/modules/home/hyprland"
  "HYPRKEYS:                  cd ~/nixos-config && $NVIM ~/nixos-config/modules/home/hyprland/config/keybindings.nix"
  ".CONFIG:                   $FM ~/.config"
  "DOWNLOADS:                 $FM ~/Downloads"
  "PICTURES:                  $FM ~/Pictures"
  "BACKGROUNDS:               $FM ~/Pictures/Backgrounds"
  "HYPR-TOGGLEANIMATIONS:     toggleanimations"
  "HYPR-COLORPICKER:          colorpicker"
  "HYPR-FOCUSWINDOW:          focuswindow tofi"
  "HYPR-TOGGLESPECIAL-MENU:   togglespecial-menu"
  "HYPR-SELECTWALLPAPER:      selectwallpaper"
  "HYPR-WALLSHIFT:            wallshift"
  "HYPR-WALLSELECT:           wallselect"
  "HYPR-KILLWALLSHIFT:        killwallshift"
  "HYPR-CLIPHIST:             cliphist list | tofi | cliphist decode | wl-copy"
  "HYPR-ERROR:                hyprctl seterror disable"
  "AGS-RESTART:               ags_restart &"
  "AGS-KILL:                  pkill ags"
  "BLUETOOTH:                 rofi-bluetooth"
  #"DUNSTRC:                   cd ~/.config/dunst && $NVIM dunstrc"
  #"FOOT:                      cd ~/.config/foot && $NVIM foot.ini"
  #"TOFI:                      cd ~/.config/tofi && $NVIM ."
  #"QUICK-LINKS:               cd ~/scripts && $NVIM quicklinks"
  #"SYNCTHING:                 xdg-open http://localhost:8384"
  #"SCRIPTS:                   cd ~/scripts && $NVIM ."
  #"AWESOME:                   cd ~/.config/awesome && $NVIM ."
  #".ZSHRC:                    cd ~/.config/zsh && $NVIM .zshrc"
  #"ROFI:                      cd ~/.config/rofi && $NVIM ."
  #"WAYBAR:                    cd ~/.config/waybar && $NVIM ."
  #"SXHKD:                     cd ~/.config/sxhkd && $NVIM sxhkdrc"
  #"MEMES:                     $FM ~/Documents/Phone\ Media/Pictures/Memes"
  #"NEOVIM:                    cd ~/.config/nvim && $NVIM ."
  #"YAZI:                      cd ~/.config/yazi && $NVIM ."
  #"RANGER:                    $FM ~/.config/ranger"
)

# Create a newline-separated string of labels for rofi
labels_string=$(printf '%s\n' "${options[@]%%:*}")

# Display labels using rofi to get the selected choice
chosen=$(echo -e "$labels_string" | $LAUNCHER)

# Find and execute the command corresponding to the chosen option
for option in "${options[@]}"; do
  if [[ "${option%%:*}" == "$chosen" ]]; then
    eval "${option#*:}"
    exit 0
  fi
done

echo "Exited."
