#!/bin/bash

TEXT=$(rofi -dmenu -p "Translate PL -> EN:" -theme ~/.config/rofi/themes/translate.rasi)

if [ -n "$TEXT" ]; then
    TRANSLATION=$(trans -b :en "$TEXT")

    echo -n "$TRANSLATION" | wl-copy

    notify-send "Translation" "$TRANSLATION"
fi
