#!/bin/bash

# Base directory where your categorized GPT prompt files are stored
BASE_PROMPT_DIR="$HOME/Documents/Obsidian/14 AI Prompts"

# Function to list all directories and files in a given directory
list_items_in_directory() {
    local dir_path=$1
    # Option to search for all files if in the base directory
    if [[ "$dir_path" == "$BASE_PROMPT_DIR" ]]; then
        echo "🔍 Search All Files"
    fi
    # Option to go back if not in the base directory
    if [[ "$dir_path" != "$BASE_PROMPT_DIR" ]]; then
        echo "🔙 ../ (Go Back)"
    fi
    # List and sort directories and files
    find "$dir_path" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; | sort | sed 's/^/📁 /'
    find "$dir_path" -mindepth 1 -maxdepth 1 -type f -exec basename {} \; | sort | sed 's/^/📄 /'
}

# Function to list all files recursively in the base directory and provide a go back option
list_all_files_recursively_with_back_option() {
    echo "🔙 ../ (Go Back)"
    find "$BASE_PROMPT_DIR" -type f -exec realpath --relative-to="$BASE_PROMPT_DIR" {} \; | sort | sed 's|^|📄 |'
}

# Recursive function for navigating directories
navigate_directories() {
    local current_path=$1
    local selection=$(list_items_in_directory "$current_path" | rofi -dmenu -i -p "Navigate (Select Folder/File):")

    if [ -n "$selection" ]; then
        # Handle special options
        if [[ "$selection" == "🔍 Search All Files" ]]; then
            selection=$(list_all_files_recursively_with_back_option | rofi -dmenu -i -p "Select a File:")
            if [[ "$selection" == "🔙 ../ (Go Back)" ]]; then
                navigate_directories "$BASE_PROMPT_DIR"
                return
            fi
        elif [[ "$selection" == "🔙 ../ (Go Back)" ]]; then
            navigate_directories "$(dirname "$current_path")"
            return
        fi

        if [ -n "$selection" ]; then
            # Remove icon from selection
            local clean_selection=${selection:2}

            if [[ "$selection" == "📄 "* ]]; then
                # Handle file selection
                local full_path="$BASE_PROMPT_DIR/$clean_selection"
                xclip -selection clipboard < "$full_path"
                echo "Content of '$clean_selection' copied to clipboard."
            else
                # Navigate into directory
                navigate_directories "$current_path/$clean_selection"
            fi
        fi
    fi
}

# Start navigation from the base prompt directory
navigate_directories "$BASE_PROMPT_DIR"
