#!/bin/bash

current_location=$(pwd)

images=$(find "$current_location" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \))

selected_image=$(for img in $images; do
    relative_path="${img#$current_location/}"
    echo -en "$relative_path\0icon\x1f$img\n"
done | rofi -dmenu -i -p "$current_location" -theme ~/.config/rofi/themes/s-img.rasi)

if [[ -n $selected_image ]]; then
    full_path="$current_location/$selected_image"
    
    action=$(echo -e "Open\nCopy image\nChange name\nOpen in GIMP\nCopy path" | rofi -dmenu -i -p "Select action" -theme ~/.config/rofi/themes/launcher3.rasi)
    
    case $action in
        "Open")
            xdg-open "$full_path"
            ;;
        "Copy image")
            mime_type=$(file --mime-type -b "$full_path")
            wl-copy -t "$mime_type" < "$full_path"
            ;;
        "Change name")
            new_name=$(rofi -dmenu -i -p "New name" -theme ~/.config/rofi/themes/launcher3.rasi -theme-str "listview { enabled: false;}")
            if [[ -n $new_name ]]; then
                extension="${full_path##*.}"
                mv "$full_path" "$(dirname "$full_path")/$new_name.$extension"
            fi
            ;;
        "Open in GIMP")
            gimp "$full_path"
            ;;
        "Copy path")
            echo -n "$full_path" | wl-copy
            ;;
        *)
            echo "Exited"
            ;;
    esac
fi

