#!/bin/bash

# Pobierz aktualną lokalizację w shellu
current_location=$(pwd)

# Lista domyślnych ścieżek
default_paths=(
    "$HOME" "$HOME/" "$HOME/Desktop" "$HOME/Downloads" "$HOME/Documents"
    "/" "/bin" "/boot" "/dev" "/etc" "/lib" "/proc" "/root" "/sbin" "/sys" "/usr" "/var"
)

# Sprawdź, czy bieżąca lokalizacja jest jedną z domyślnych ścieżek
for path in "${default_paths[@]}"; do
    if [[ "$current_location" == "$path" ]]; then
        echo "Exited. One of the default paths ($path)."
        notify-send "Exited." "One of the default paths ($path)."
        exit 0
    fi
done

# Sprawdź, czy podano argument -o
if [[ "$1" == "-o" ]]; then
    # Znajdź wszystkie obrazy tylko w bieżącej lokalizacji
    images=$(find "$current_location" -maxdepth 1 -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \))
else
    # Znajdź wszystkie obrazy w bieżącej lokalizacji i jej podkatalogach
    images=$(find "$current_location" -type f \( -iname "*.jpg" -o -iname "*.png" -o -iname "*.jpeg" \))
fi

# Wyświetl menu z listą obrazów (tylko nazwy plików z podkatalogami)
selected_image=$(for img in $images; do
    # Usuń bieżącą lokalizację z pełnej ścieżki, aby uzyskać ścieżkę względną
    relative_path="${img#$current_location/}"
    echo -en "$relative_path\0icon\x1f$img\n"
done | rofi -dmenu -i -p "$current_location" -theme ~/.config/rofi/themes/sig.rasi)

# Jeśli wybrano obraz
if [[ -n $selected_image ]]; then
    full_path="$current_location/$selected_image"
    
    # Wyświetl menu z opcjami dla wybranego obrazu
    action=$(echo -e "Open\nCopy image\nChange name\nOpen in GIMP\nCopy path" | rofi -dmenu -i -p "Select action" -theme ~/.config/rofi/themes/launcher3.rasi)
    
    case $action in
        "Open")
            xdg-open "$full_path"
            ;;
        "Copy image")
            mime_type=$(file --mime-type -b "$full_path")
            wl-copy -t "$mime_type" < "$full_path"
            ;;
        "Change name")
            new_name=$(rofi -dmenu -i -p "New name" -theme ~/.config/rofi/themes/launcher3.rasi -theme-str "listview { enabled: false;}")
            if [[ -n $new_name ]]; then
                extension="${full_path##*.}"
                mv "$full_path" "$(dirname "$full_path")/$new_name.$extension"
            fi
            ;;
        "Open in GIMP")
            gimp "$full_path"
            ;;
        "Copy path")
            echo -n "$full_path" | wl-copy
            ;;
        *)
            echo "Exited"
            ;;
    esac
fi

