#!/bin/bash

active=$(hyprctl -j monitors | jq -r '.[] | select(.focused==true).specialWorkspace.name')

if [[ $active != "" ]]; then
    if [[ $active == "special:"* ]]; then
        active=${active#special:}
    elif [[ $active == "special" ]]; then
        active=""
    fi
    hyprctl dispatch togglespecialworkspace "$active"
fi

while getopts "w:x:" opt; do
  case ${opt} in
    w )
      hyprctl dispatch workspace "${OPTARG}"
      ;;
    x )
      hyprctl dispatch focusworkspaceoncurrentmonitor "${OPTARG}"
      ;;
  esac
done