#!/bin/bash

STORE_FILE="/tmp/dynamicwindow"

if [ ! -f "$STORE_FILE" ]; then
	touch "$STORE_FILE"
fi

toggle_dynamic() {
	workspace_name="$1"
	active_window=$(hyprctl -j activewindow | jq -r '.address')
	active_workspace=$(hyprctl -j activeworkspace | jq -r '.name')

	if [ "$active_window" != "null" ]; then
		window_workspace=$(hyprctl -j clients | jq --arg ADDRESS "$active_window" '.[] | select(.address == $ADDRESS)' | jq -r '.workspace.name')
		if grep -q "$active_window" "$STORE_FILE"; then
			sed -i "/$active_window/d" "$STORE_FILE"
			hyprctl notify -1 1500 "rgb(98971a)" "Dynamic Window - Removed" 
		elif [ "$window_workspace" != "$workspace_name" ]; then
			echo "$active_window $workspace_name" >>"$STORE_FILE"
			hyprctl dispatch movetoworkspacesilent "$workspace_name","address:$active_window"
			hyprctl notify -1 1500 "rgb(98971a)" "Dynamic Window - Added" 
		fi
	else
		hyprctl notify -1 1500 "rgb(98971a)" "No active window"
	fi
}

view_dynamic() {
	workspace_name="$1"
	active_workspace=$(hyprctl activeworkspace -j | jq -r '.name')

	any_windows_moved=0
	while IFS= read -r line; do
		window_address=$(echo "$line" | cut -d ' ' -f 1)
		dynamic_workspace=$(echo "$line" | cut -d ' ' -f 2)
		window_workspace=$(hyprctl -j clients | jq --arg ADDRESS "$window_address" '.[] | select(.address == $ADDRESS)' | jq -r '.workspace.name')
		if [ "$window_workspace" == "$active_workspace" ] && [ "$dynamic_workspace" == "$workspace_name" ]; then
			hyprctl dispatch movetoworkspacesilent "$dynamic_workspace","address:$window_address"
			any_windows_moved=1
		fi
	done <"$STORE_FILE"

	if [ "$any_windows_moved" -eq 0 ]; then
		while IFS= read -r line; do
			window_address=$(echo "$line" | cut -d ' ' -f 1)
			dynamic_workspace=$(echo "$line" | cut -d ' ' -f 2)
			window_workspace=$(hyprctl -j clients | jq --arg ADDRESS "$window_address" '.[] | select(.address == $ADDRESS)' | jq -r '.workspace.name')
			if [ "$dynamic_workspace" == "$workspace_name" ] && [ "$window_workspace" != "$active_workspace" ]; then
				hyprctl dispatch movetoworkspace "$active_workspace","address:$window_address"
			fi
		done <"$STORE_FILE"
	fi
}

case "$1" in
  -t)
    if [ -z "$2" ]; then
        echo "Specify a special workspace"
        exit 1
    fi
    toggle_dynamic "$2"
    ;;
  -v)
    if [ -z "$2" ]; then
        echo "Specify a special workspace"
        exit 1
    fi
    view_dynamic "$2"
    ;;
  *)
    echo "Invalid option: $1"
    exit 1
    ;;
esac