#!/bin/bash

# Usage: focuswindow tofi/rofi/wofi

window_list=$(hyprctl -j clients | jq -r '.[] | "\(.title) | \(.address)"')

declare -A window_map
updated_window_list=""
index=1

while IFS= read -r line; do
    window_address=${line##* | }
    window_map[$index]=$window_address
    updated_window_list+="$index | ${line% | *}"$'\n'
    let index=index+1
done <<<"$window_list"

selected_window=$(echo -e "$updated_window_list" | $1)

window_id=${selected_window%% | *}
window_address=${window_map[$window_id]}

if [ -z "$window_address" ]; then
    echo "No window selected."
    exit 1
fi

# Do czasu aż focusowanie okna będąc w special workspace'ie nie zamknie automatycznie special workspace'u. Powinienem utworzyć issue na githubie
selected_window_workspace=$(hyprctl -j clients | jq -r ".[] | select(.address==\"$window_address\") | .workspace.name")
active_monitor=$(hyprctl -j monitors | jq '.[] | select(.focused==true)')

if [ -n "$(echo "$active_monitor" | jq -r '.specialWorkspace.name')" ] && [[ "$selected_window_workspace" != *"special"* ]]; then
    $HOME/.config/hypr/scripts/closespecial
fi

hyprctl dispatch focuswindow "address:$window_address"

