#!/bin/bash

# TODO - skrypt nie dziala poprawnie w nixos

# Kill waybar
pkill waybar

# Kill scripts
pkill windowstate

# Wait for the processes to end
# Waybar
while pgrep -u $UID -x waybar >/dev/null; do sleep 0.1; done

# Start the waybar
nohup waybar &> /dev/null &

# Launch scirpts
~/.config/waybar/scripts/windowstate