#!/usr/bin/env bash
rofi_command="rofi -markup -markup-rows -theme $HOME/.config/rofi/themes/launcher.rasi"

datetime=$(date +"%Y-%m-%d %I-%M-%S")
dir="$HOME/Videos/Screen-Recordings"

# Icons
icon1="$HOME/.config/rofi/images/camera-movie.svg"
icon2="$HOME/.config/rofi/images/timer.svg"

screen="  Record Desktop"
area="  Record Area"
window="  Record Window"
infivearea="  Record Area in 5s"
infive="  Record in 5s"

# Notify and view screenshot
notify_view () {
	dunstify -u low --replace=699 -i $icon1 "Copied to clipboard."
	if [[ -e "$dir/Screen Recording from ${datetime}.mkv" ]]; then
		echo "$dir/Screen Recording from ${datetime}.mkv"
		action=$(dunstify --action="default,openss" -u low --replace=699 -i $icon1 "Screen Recording Saved.")
		case "$action" in
		"default")
		    xdg-open "$dir/Screen Recording from ${datetime}.mkv"
		    ;;
		esac		
	else
		dunstify -u low --replace=699 -i $icon1 "Screen Recording Deleted."
	fi
}

# countdown
countdown () {
	for sec in `seq $1 -1 1`; do
		dunstify -t 1000 --replace=699 -i $icon2 "Recording in : $sec"
		sleep 1
	done
}

# take shots
recordnow () {
	sleep 0.5 && wl-screenrec -g "0,0 1920x1080" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy < $dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

record5 () {
	countdown '5'
	sleep 1 &&  wf-recorder -g "0,0 1920x1080" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy < $dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

record5area () {
	countdown '5'
	sleep 1 &&  wl-screenrec -g "$(slurp -b#0f0f0f78 -c#cc7765 -w4)" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy < $dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

recordwin () {
	geometry=$(hyprctl activewindow -j | jq -r '"\(.at[0]),\(.at[1]) \(.size[0])x\(.size[1])"')
	sleep 1 & wl-screenrec -g "${geometry}" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy < $dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

recordarea () {
	wl-screenrec -g "$(slurp -b#0f0f0f78 -c#cc7765 -w4)" -f $dir/"Screen Recording from ${datetime}".mkv
	wl-copy < $dir/"Screen Recording from ${datetime}".mkv
	notify_view
}

if [[ ! -d "$dir/" ]]; then
	mkdir -p "$dir/"
fi

# Variable passed to rofi
options="$screen\n$area\n$window\n$infivearea\n$infive"

chosen="$(echo -e "$options"| $rofi_command -p 'Screen Recording' -dmenu -selected-row 0)"
case $chosen in
    $screen)
		recordnow
        ;;
    $area)
		recordarea
        ;;
    $window)
		recordwin
		;;
    $infive)
		record5
		;;
    $infivearea)
		record5area
        ;;
esac
