#!/bin/sh

# Reset files
for monitor in $(hyprctl -j monitors | jq -r '.[].id'); do
    echo "" > "/tmp/windowstate_$monitor"
done

handle() {
	case $1 in
	activewindow* | fullscreen* | changefloatingmode*)
		# Fetch monitor IDs
		monitors=$(hyprctl -j monitors | jq -r '.[].id')

		for monitor in $monitors; do
			# Fetch the active workspace or special workspace on the monitor
			active_workspace=$(hyprctl -j monitors | jq -r --argjson monitor "$monitor" '
				.[] | select(.id == $monitor) | 
				if .specialWorkspace.id != 0 then 
					.specialWorkspace.id 
				else 
					.activeWorkspace.id 
				end')

			# Fetch the last window on the active workspace
			lastwindow=$(hyprctl -j workspaces | jq -r --argjson workspace "$active_workspace" '.[] | select(.id == $workspace) | .lastwindow')

			# Fetch the state of the last window
			fullscreen=$(hyprctl -j clients | jq -r --arg lastwindow "$lastwindow" 'map(select(.address == $lastwindow)) | .[0].fullscreen')
			floating=$(hyprctl -j clients | jq -r --arg lastwindow "$lastwindow" 'map(select(.address == $lastwindow)) | .[0].floating')

			if [ "$fullscreen" = 1 ] || [ "$fullscreen" = 2 ]; then
				if [ "$floating" = true ]; then
					output="Floating - Fullscreen"
				else
					output="Fullscreen"
				fi
			elif [ "$floating" = true ]; then
				output="Floating"
			elif [ "$floating" = false ]; then
				output="Tiled"
			else
				output=""
			fi

			# Save the result to a monitor-specific file
			echo "$output" > "/tmp/windowstate_$monitor"
		done

		# Send a signal to waybar
		pkill -RTMIN+8 waybar
		;;
	esac
}

socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done